# Generated by Django 3.1.7 on 2022-04-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRecon', '0002_settingqueries'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconfileuploads',
            name='system_comments',
            field=models.TextField(null=True, verbose_name='System Comments'),
        ),
    ]
