# Generated by Django 3.1.7 on 2022-04-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRecon', '0004_recoexecutiontasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoexecutiontasks',
            name='description',
            field=models.TextField(null=True, verbose_name='Procedure Description'),
        ),
    ]
