# Generated by Django 3.1.7 on 2022-04-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRecon', '0005_recoexecutiontasks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='processing_date_time',
            field=models.CharField(max_length=64, null=True, verbose_name='Processing Date Time'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='processing_date_time',
            field=models.CharField(max_length=64, null=True, verbose_name='Processing Date Time'),
        ),
        migrations.AlterField(
            model_name='transactionexternalrecords',
            name='processing_date_time',
            field=models.CharField(max_length=64, null=True, verbose_name='Processing Date Time'),
        ),
        migrations.AlterField(
            model_name='transactioninternalrecords',
            name='processing_date_time',
            field=models.CharField(max_length=64, null=True, verbose_name='Processing Date Time'),
        ),
    ]
