# Generated by Django 3.1.7 on 2022-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRecon', '0006_auto_20220418_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoexecutiontasks',
            name='created_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='recoexecutiontasks',
            name='modified_date',
            field=models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='reconfileuploads',
            name='created_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='reconfileuploads',
            name='modified_date',
            field=models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='recoresults',
            name='created_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='recoresults',
            name='modified_date',
            field=models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='recosettings',
            name='created_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='recosettings',
            name='modified_date',
            field=models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='settingqueries',
            name='created_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='settingqueries',
            name='modified_date',
            field=models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='created_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='modified_date',
            field=models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='created_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='modified_date',
            field=models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='stagingrecoresults',
            name='created_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='stagingrecoresults',
            name='modified_date',
            field=models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='transactionexternalrecords',
            name='created_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='transactionexternalrecords',
            name='modified_date',
            field=models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='transactioninternalrecords',
            name='created_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='transactioninternalrecords',
            name='modified_date',
            field=models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='vendormaster',
            name='created_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='vendormaster',
            name='modified_date',
            field=models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
    ]
