# Generated by Django 3.1.7 on 2022-04-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRecon', '0007_auto_20220418_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='entities_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Entities Id (Business Module - Entities Id)'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='file_uploads_id',
            field=models.PositiveIntegerField(null=True, verbose_name='File Uploads Id (Recon Module - File Uploads Id)'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='groups_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Groups Id (Business Module - Groups Id)'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='m_sources_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Sources Id (Sources Module - Sources Id)'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='staging_row_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Staging Row Id (Staging Table - Row Id)'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='tenants_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Tenants Id (Business Module - Tenant Id)'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='entities_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Entities Id (Business Module - Entities Id)'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='file_uploads_id',
            field=models.PositiveIntegerField(null=True, verbose_name='File Uploads Id (Recon Module - File Uploads Id)'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='groups_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Groups Id (Business Module - Groups Id)'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='m_sources_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Sources Id (Sources Module - Sources Id)'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='staging_row_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Staging Row Id (Staging Table - Row Id)'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='tenants_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Tenants Id (Business Module - Tenant Id)'),
        ),
        migrations.AlterField(
            model_name='transactionexternalrecords',
            name='entities_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Entities Id (Business Module - Entities Id)'),
        ),
        migrations.AlterField(
            model_name='transactionexternalrecords',
            name='file_uploads_id',
            field=models.PositiveIntegerField(null=True, verbose_name='File Uploads Id (Recon Module - File Uploads Id)'),
        ),
        migrations.AlterField(
            model_name='transactionexternalrecords',
            name='groups_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Groups Id (Business Module - Groups Id)'),
        ),
        migrations.AlterField(
            model_name='transactionexternalrecords',
            name='m_sources_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Sources Id (Sources Module - Sources Id)'),
        ),
        migrations.AlterField(
            model_name='transactionexternalrecords',
            name='staging_row_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Staging Row Id (Staging Table - Row Id)'),
        ),
        migrations.AlterField(
            model_name='transactionexternalrecords',
            name='tenants_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Tenants Id (Business Module - Tenant Id)'),
        ),
        migrations.AlterField(
            model_name='transactioninternalrecords',
            name='entities_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Entities Id (Business Module - Entities Id)'),
        ),
        migrations.AlterField(
            model_name='transactioninternalrecords',
            name='file_uploads_id',
            field=models.PositiveIntegerField(null=True, verbose_name='File Uploads Id (Recon Module - File Uploads Id)'),
        ),
        migrations.AlterField(
            model_name='transactioninternalrecords',
            name='groups_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Groups Id (Business Module - Groups Id)'),
        ),
        migrations.AlterField(
            model_name='transactioninternalrecords',
            name='m_sources_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Sources Id (Sources Module - Sources Id)'),
        ),
        migrations.AlterField(
            model_name='transactioninternalrecords',
            name='staging_row_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Staging Row Id (Staging Table - Row Id)'),
        ),
        migrations.AlterField(
            model_name='transactioninternalrecords',
            name='tenants_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Tenants Id (Business Module - Tenant Id)'),
        ),
    ]
