# Generated by Django 3.1.7 on 2022-04-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRecon', '0009_auto_20220418_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoexecutionlog',
            name='row_count',
            field=models.PositiveIntegerField(null=True, verbose_name='Row Count'),
        ),
    ]
