# Generated by Django 3.1.7 on 2022-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRecon', '0010_recoexecutionlog_row_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMatchingDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(null=True, verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(null=True, verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(null=True, verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Layer Id')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(null=True, verbose_name='M Processing Sub Layer Id')),
                ('processing_layer_id', models.PositiveIntegerField(null=True, verbose_name='Processing Layer Id')),
                ('vendor_master_id', models.PositiveIntegerField(null=True, verbose_name='Vendor Master Id')),
                ('vendor_code', models.CharField(max_length=64, null=True, verbose_name='Vendor Code')),
                ('vendor_name', models.CharField(max_length=512, null=True, verbose_name='Vendor Name')),
                ('vendor_site_code', models.CharField(max_length=128, null=True, verbose_name='Vendor Site Code')),
                ('vendor_category', models.CharField(max_length=128, null=True, verbose_name='Vendor Category')),
                ('liability_account', models.CharField(max_length=512, null=True, verbose_name='Liability Account')),
                ('contact_first_name', models.CharField(max_length=256, null=True, verbose_name='Contact First Name')),
                ('contact_phone_number', models.CharField(max_length=64, null=True, verbose_name='Contact Phone Number')),
                ('contact_email', models.CharField(max_length=512, null=True, verbose_name='Contact Email Address')),
                ('division', models.CharField(max_length=128, null=True, verbose_name='Division')),
                ('pan_number', models.CharField(max_length=15, null=True, verbose_name='PAN Number')),
                ('gst_number', models.CharField(max_length=20, null=True, verbose_name='GST Number')),
                ('vendor_type', models.CharField(max_length=64, null=True, verbose_name='Vendor Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.CharField(max_length=64, null=True, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(max_length=64, null=True, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'vendor_matching_details',
            },
        ),
        migrations.AlterField(
            model_name='recoexecutiontasks',
            name='entities_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Entities Id (Business Module - Entities Id)'),
        ),
        migrations.AlterField(
            model_name='recoexecutiontasks',
            name='execution_sequence',
            field=models.PositiveIntegerField(null=True, verbose_name='Execution Sequence'),
        ),
        migrations.AlterField(
            model_name='recoexecutiontasks',
            name='groups_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Groups Id (Business Module - Groups Id)'),
        ),
        migrations.AlterField(
            model_name='recoexecutiontasks',
            name='m_processing_layer_id',
            field=models.PositiveIntegerField(null=True, verbose_name='M Processing Layer Id'),
        ),
        migrations.AlterField(
            model_name='recoexecutiontasks',
            name='m_processing_sub_layer_id',
            field=models.PositiveIntegerField(null=True, verbose_name='M Processing Sub Layer Id'),
        ),
        migrations.AlterField(
            model_name='recoexecutiontasks',
            name='processing_layer_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Processing Layer Id'),
        ),
        migrations.AlterField(
            model_name='recoexecutiontasks',
            name='tenants_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Tenants Id (Business Module - Tenant Id)'),
        ),
        migrations.AlterField(
            model_name='settingqueries',
            name='entities_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Entities Id (Business Module - Entities Id)'),
        ),
        migrations.AlterField(
            model_name='settingqueries',
            name='groups_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Groups Id (Business Module - Groups Id)'),
        ),
        migrations.AlterField(
            model_name='settingqueries',
            name='tenants_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Tenants Id (Business Module - Tenant Id)'),
        ),
    ]
