# Generated by Django 3.1.7 on 2022-04-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRecon', '0012_mastermatchingcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastermatchingcomments',
            name='processing_layer_id',
        ),
    ]
