# Generated by Django 3.1.7 on 2022-04-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorRecon', '0013_remove_mastermatchingcomments_processing_layer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermatchingcomments',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='recoexecutiontasks',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='reconfileuploads',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='recoresults',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='recosettings',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='settingqueries',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='stagingexternalrecords',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='staginginternalrecords',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='stagingrecoresults',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='transactionexternalrecords',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='transactioninternalrecords',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='vendormaster',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='vendormatchingdetails',
            name='modified_date',
            field=models.CharField(max_length=64, null=True, verbose_name='Modified Date'),
        ),
    ]
